In [99]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [137]:
dataset = pd.read_csv('Data2.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [138]:
print(x)

[['Apple' 44.0 72000.0]
 ['Banana' 27.0 48000.0]
 ['Orange' 30.0 54000.0]
 ['Grapes' 38.0 61000.0]
 ['Pineapple' 40.0 nan]
 ['Mango' 35.0 58000.0]
 ['Melon' nan 52000.0]
 ['Avocado' 48.0 79000.0]]


In [139]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes']


In [140]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])


In [141]:
print(x)

[['Apple' 44.0 72000.0]
 ['Banana' 27.0 48000.0]
 ['Orange' 30.0 54000.0]
 ['Grapes' 38.0 61000.0]
 ['Pineapple' 40.0 60571.42857142857]
 ['Mango' 35.0 58000.0]
 ['Melon' 37.42857142857143 52000.0]
 ['Avocado' 48.0 79000.0]]


In [142]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [143]:
print(x)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 27.0 48000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 38.0 61000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 40.0 60571.42857142857]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 37.42857142857143 52000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 48.0 79000.0]]


In [144]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder();
y = le.fit_transform(y)

In [145]:
print(y)

[0 1 0 0 1 1 0 1]


In [146]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)


In [147]:
print(x_train)

[[0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 27.0 48000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 37.42857142857143 52000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 40.0 60571.42857142857]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 38.0 61000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 35.0 58000.0]]


In [148]:
print(x_test)

[[0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 30.0 54000.0]]


In [149]:
print(y_train)

[1 0 0 1 0 1]


In [150]:
print(y_test)

[1 0]


In [151]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [152]:
print(x_train)

[[0.0 0.0 1.0 -0.4472135954999579 -0.44721359549995787
  -0.44721359549995787 0.0 -0.44721359549995787 -1.8995631823052483
  -1.3962747073874662]
 [0.0 0.0 0.0 -0.4472135954999579 -0.44721359549995787 2.2360679774997894
  0.0 -0.44721359549995787 0.10045766829498941 -0.8691417841490521]
 [1.0 0.0 0.0 -0.4472135954999579 -0.44721359549995787
  -0.44721359549995787 0.0 -0.44721359549995787 1.3607447796321248
  1.7665228320430177]
 [0.0 0.0 0.0 -0.4472135954999579 -0.44721359549995787
  -0.44721359549995787 0.0 2.2360679774997894 0.59361349447039
  0.2604287656475494]
 [0.0 0.0 0.0 2.23606797749979 -0.44721359549995787 -0.44721359549995787
  0.0 -0.44721359549995787 0.21004785188952257 0.3169072931373793]
 [0.0 0.0 0.0 -0.4472135954999579 2.2360679774997894 -0.44721359549995787
  0.0 -0.44721359549995787 -0.36530061198177854 -0.07844239929143115]]


In [153]:
print(x_test)

[[0.0 1.0 0.0 -0.4472135954999579 -0.44721359549995787
  -0.44721359549995787 0.0 -0.44721359549995787 2.1278760647938597
  2.689005447710242]
 [0.0 0.0 0.0 -0.4472135954999579 -0.44721359549995787
  -0.44721359549995787 1.0 -0.44721359549995787 -1.324214718433947
  -0.6055753225298451]]
